apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    environment: {{ .Values.environment }}
    app.kubernetes.io/managed-by: Helm
type: Opaque
stringData:
  JWT_SECRET_KEY: "{{ .Values.jwt.secret }}" 