apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: zmnnoory-hpa
  namespace: zmnnoory
  labels:
    app: zmnnoory-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: zmnnoory-backend
  
  # 최소/최대 Pod 수 설정
  minReplicas: 2     # 최소 2개 유지
  maxReplicas: 10    # 최대 10개까지 확장
  
  # 스케일링 정책
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  # 5분 안정화
      policies:
      - type: Percent
        value: 50        # 50%씩 축소
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60   # 1분 안정화
      policies:
      - type: Percent
        value: 100       # 100%씩 확장 (2배)
        periodSeconds: 60
      - type: Pods
        value: 2         # 또는 최대 2개씩 추가
        periodSeconds: 60
      selectPolicy: Max  # 더 적극적인 정책 선택
  
  # 메트릭 기반 스케일링
  metrics:
  # CPU 사용률 기반
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70  # CPU 70% 초과 시 확장
  
  # 메모리 사용률 기반 (선택사항)
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80  # 메모리 80% 초과 시 확장 