apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 네임스페이스 설정
namespace: zmnnoory

# 공통 라벨 추가
commonLabels:
  app: zmnnoory-backend
  project: zmnnoory
  environment: production

# 모든 리소스 파일 포함
resources:
  - 00-nginx-ingress-controller.yaml  # NGINX Ingress Controller
  - 01-namespace.yaml
  - 02-configmap.yaml
  - 03-secret.yaml
  - 04-deployment.yaml
  - 05-service.yaml
  - 06-hpa.yaml
  - 07-ingress.yaml

# 이미지 태그 관리 (GitLab CI에서 동적으로 변경)
images:
  - name: your-registry/zmnnoory
    newTag: latest

# ConfigMap 생성기 (추가 설정 파일이 있는 경우)
# configMapGenerator:
#   - name: app-config
#     files:
#       - application-k8s.yml

# Secret 생성기 (파일 기반 시크릿 생성 시)
# secretGenerator:
#   - name: app-secrets
#     files:
#       - jwt-key.txt

# 리소스 변형 설정
patches:
  # 환경별 리소스 조정 (예: 개발환경에서는 replicas 줄이기)
  - target:
      kind: Deployment
      name: zmnnoory-backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3

# 대체 설정 (환경변수나 설정값 변경)
replicas:
  - name: zmnnoory-backend
    count: 3 