### create member fail 1
POST http://localhost:8080/api/members/sign-up
Content-Type: application/json

{
  "email" : "test1stest.com",
  "password": "123123123",
  "gender": "bird",
  "nickname": "tester",
  "birthday": "2000-01-01"
}

### check nickname duplicated
GET http://localhost:8080/api/members/check-nickname?nickname=tester
Content-Type: application/json

### check email duplicated
GET http://localhost:8080/api/members/check-email?email=test1@test.com

### create member1
POST http://localhost:8080/api/members/sign-up
Content-Type: application/json

{
  "email" : "test1@test.com",
  "password": "123123123",
  "gender": "MALE",
  "nickname" : "tester",
  "birthday": "2000-01-01"
}

### create member fail - duplicated
POST http://localhost:8080/api/members/sign-up
Content-Type: application/json

{
  "email" : "test1@test.com",
  "password": "123123123",
  "gender": "MALE",
  "nickname" : "tester",
  "birthday": "2000-01-01"
}

### create member2
POST http://localhost:8080/api/members/sign-up
Content-Type: application/json

{
  "email" : "test2@test.com",
  "password": "123123123",
  "gender": "MALE",
  "nickname" : "tester2",
  "recommenderEmail": "test1@test.com",
  "birthday": "2000-01-01"
}

### login fail
POST http://localhost:8080/api/members/login
Content-Type: application/json

{
  "email" : "fail@test.com",
  "password" : "123123123"
}

### login success
POST http://localhost:8080/api/members/login
Content-Type: application/json

{
  "email" : "test1@test.com",
  "password" : "123123123"
}

> {%
    // Authorization 헤더 값을 가져와 전역 변수에 저장
    client.global.set("auth", response.body.body.data);
%}

###
GET http://localhost:8080/api/members/me
Content-Type: application/json
Authorization: Bearer {{auth}}

### login success
POST http://localhost:8080/api/members/login
Content-Type: application/json

{
  "email" : "test2@test.com",
  "password" : "123123123"
}

> {%
    // Authorization 헤더 값을 가져와 전역 변수에 저장
    client.global.set("auth", response.body.body.data);
%}

### admin required request
GET http://localhost:8080/api/members/admin
Authorization: Bearer {{auth}}

### password update
PATCH http://localhost:8080/api/members/password
Content-Type: application/json
Authorization: Bearer {{auth}}

{
  "originPassword": "123123123",
  "updatedPassword" : "321321321"
}

