namespace: backend-dev
environment: dev

spring:
  profile: k8s

# Database Configuration (will be overridden by CI/CD)
database:
  url: "jdbc:postgresql://3.38.95.2:5432/development_db"
  username: "root"
  password: "q1w2e3r4t5"
  
# Redis Configuration (will be overridden by CI/CD)
redis:
  host: "3.38.95.2"
  port: "6379"
  password: ""

# JWT Configuration (will be overridden by CI/CD)
jwt:
  secret: "em1ubm9ycnltZW1iZXJzY2FuZ2V0YWpvYnRoYXR0aGV5d2FudGlzdXJlZm9ydGhhdHNzYWZ5d291bGRoZWxwdXNmb3J0aGF0Y29tZXRydWU="
  issuer: "ZMNNOORY"
  expiration: "3h"
  prefix: "Bearer "
  header: "Authorization"

# Application Configuration
app:
  name: "ZMNNOORY"

# Default values for zmnnoory-backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: "localhost:32000/zmnnoory-backend"
  tag: "__TAG__"
  pullPolicy: Always

replicaCount: 3

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
  host: "ec2-3-38-95-2.ap-northeast-2.compute.amazonaws.com"
  path: "/"

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
